# Generated by Django 3.2.6 on 2021-08-29 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
